/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionpedidos;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Action;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Sergio
 */
public class NewJFrame1 extends javax.swing.JFrame implements ListCellRenderer {

    /**
     * Creates new form NewJFrame1
     */
    public String n;

    public NewJFrame1() {

        //initComponents();
        // this.setUndecorated(false);
    }

    public NewJFrame1(String nombreEmpleado) {
        initComponents();
        n = nombreEmpleado;
        jTextField2Nombre.setEnabled(false);
        jTextField3Direccion.setEnabled(false);
        jTextField4Numero.setEnabled(false);
        jTextField5Piso.setEnabled(false);
        jTextField7Puerta.setEnabled(false);
        jButtonModfiDatos.setEnabled(false);
        jTextField1Portal.setEnabled(false);
        jTextField2Escalera.setEnabled(false);
        jButton1.setVisible(false);
        jButton2AceptarDatosNuevos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jLabel2Nombre = new javax.swing.JLabel();
        jTextField2Nombre = new javax.swing.JTextField();
        jLabel3Direccion = new javax.swing.JLabel();
        jTextField3Direccion = new javax.swing.JTextField();
        jLabel4Numero = new javax.swing.JLabel();
        jTextField4Numero = new javax.swing.JTextField();
        jLabel5Piso = new javax.swing.JLabel();
        jTextField5Piso = new javax.swing.JTextField();
        jLabel6Puerta = new javax.swing.JLabel();
        jTextField7Puerta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1Portal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2Escalera = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2AceptarDatosNuevos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonModfiDatos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(125, 400));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(590, 353));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(33000, 33000));

        jLabelTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTelefono.setText("Teléfono:");
        jLabelTelefono.setToolTipText("");

        jTextFieldTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTelefonoFocusLost(evt);
            }
        });
        jTextFieldTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonoKeyReleased(evt);
            }
        });

        jButtonAceptar.setBackground(new java.awt.Color(255, 204, 204));
        jButtonAceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAceptar.setForeground(new java.awt.Color(0, 153, 0));
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jLabel2Nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2Nombre.setText("Nombre:");

        jTextField2Nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3Direccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3Direccion.setText("Calle:");

        jTextField3Direccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4Numero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4Numero.setText("Número:");

        jTextField4Numero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5Piso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5Piso.setText("Piso:");

        jTextField5Piso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6Puerta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6Puerta.setText("Puerta:");

        jTextField7Puerta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Portal:");

        jTextField1Portal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Escalera:");

        jTextField2Escalera.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2Escalera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2EscaleraActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("*");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("*");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("*");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 0));
        jLabel8.setText("*");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Viv:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 0));
        jLabel10.setText("*");

        jComboBox1.setBackground(new java.awt.Color(255, 153, 153));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O - Oficina", "P - Casa particular", "R - Otros", "H - Hotel", "C - Colegio", "T - Hospital", "G - Poligono industrial", "E - Residencia", " " }));
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
        });

        jButton2AceptarDatosNuevos.setBackground(new java.awt.Color(255, 204, 204));
        jButton2AceptarDatosNuevos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2AceptarDatosNuevos.setForeground(new java.awt.Color(0, 153, 0));
        jButton2AceptarDatosNuevos.setText("Aceptar");
        jButton2AceptarDatosNuevos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2AceptarDatosNuevosActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DATOS DEL CLIENTE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));

        jButton9.setBackground(new java.awt.Color(255, 204, 204));
        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 153, 0));
        jButton9.setText("F2/Clave");
        jButton9.setOpaque(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 204, 204));
        jButton10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 153, 0));
        jButton10.setText("F3/Aborta");
        jButton10.setOpaque(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 0));
        jButton1.setText("F5/PedNuevo");

        jButtonModfiDatos.setBackground(new java.awt.Color(255, 204, 204));
        jButtonModfiDatos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonModfiDatos.setForeground(new java.awt.Color(0, 153, 0));
        jButtonModfiDatos.setText("F8/Modf Datos");
        jButtonModfiDatos.setOpaque(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonModfiDatos))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton9)
                .addComponent(jButton10)
                .addComponent(jButton1)
                .addComponent(jButtonModfiDatos))
        );

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpedidos/Sin título-1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 78, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3Direccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelTelefono)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel2Nombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField2Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextField3Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4Numero))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextField1Portal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jTextField2Escalera, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel5Piso)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel8)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTextField5Piso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jButtonAceptar)
                                                    .addComponent(jButton2AceptarDatosNuevos))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6Puerta)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField7Puerta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField4Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(151, 151, 151))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2Nombre)
                    .addComponent(jTextField2Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3Direccion)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4Numero)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1Portal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2Escalera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5Piso)
                    .addComponent(jLabel8)
                    .addComponent(jTextField5Piso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6Puerta)
                    .addComponent(jTextField7Puerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2AceptarDatosNuevos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2AceptarDatosNuevosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2AceptarDatosNuevosActionPerformed
        // Botón aceptar datos nuevos, cuando un cliente no existe en la base de datos.
        Connection conexion;
        try {
            conexion = DriverManager.getConnection("jdbc:mysql://sql7.freesqldatabase.com/sql7143904", "sql7143904", "TzNhGaxJj6");
            Statement sentencia = conexion.createStatement();
            int telefono = Integer.valueOf(jTextFieldTelefono.getText());
            String nombre = jTextField2Nombre.getText();
            String calle = jTextField3Direccion.getText();
            int numero = Integer.valueOf(jTextField4Numero.getText());
            int portal = Integer.valueOf(jTextField1Portal.getText());
            String escalera = jTextField2Escalera.getText();
            String piso = jTextField5Piso.getText();
            String puerta = jTextField7Puerta.getText();

            //            ResultSet result =
            sentencia.executeUpdate("INSERT INTO sql7143904.clientes (telefono, nombre, calle, numero, piso, puerta, portal, escalera) VALUES ('"+telefono+"', '"+nombre+"', '"+calle+"', '"+numero+"', '"+piso+"', '"+puerta+"', '"+portal+"', '"+escalera+"');");
        } catch (SQLException ex) {
            System.out.println("Error en la conexión " + ex.toString());
        }
    }//GEN-LAST:event_jButton2AceptarDatosNuevosActionPerformed

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained
        // Método para cuando el comboBox gana el foco.
        jComboBox1.setBackground(Color.PINK);
    }//GEN-LAST:event_jComboBox1FocusGained

    private void jTextField2EscaleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2EscaleraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2EscaleraActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // Botón aceptar datos
        //CONEXIÓN A LA BASE DE DATOS
        try {
            //Asignar el driver de la base de datos.
            Class.forName("com.mysql.jdbc.Driver");
            //Establecemos la conexión con la base de datos.
            Connection conexion = DriverManager.getConnection("jdbc:mysql://sql7.freesqldatabase.com/sql7143904", "sql7143904", "TzNhGaxJj6");
            //Realizar la consulta y recoger el resultado en un objeto ResulSet.
            Statement sentencia = conexion.createStatement();
            int telefono = Integer.parseInt(jTextFieldTelefono.getText());
            ResultSet resul = sentencia.executeQuery("Select nombre,calle, numero,piso,puerta from clientes where telefono=" + telefono + "");
            //Mostrar el resultado de la consulta.

            while (resul.next()) {
                if (resul.getString(1).equals(0)) {
                    JOptionPane.showMessageDialog(rootPane, "¡No existe empleado con esa clave! ");

                    //System.out.println(telefono);
                } else {
                    jTextField2Nombre.setText(resul.getString(1));
                    jTextField3Direccion.setText(resul.getString(2));
                    jTextField4Numero.setText(String.valueOf(resul.getInt(3)));
                    jTextField5Piso.setText(resul.getString(4));
                    jTextField7Puerta.setText(resul.getString(5));
                    //Existe el cliente, por lo que anulamos el poder editar los campos.
                    jTextField2Nombre.setEditable(false);
                    jTextField3Direccion.setEditable(false);
                    jTextField4Numero.setEditable(false);
                    jTextField1Portal.setEditable(false);
                    jTextField2Escalera.setEditable(false);
                    jTextField5Piso.setEditable(false);

                    //Existe el cliente, por lo que podemos modificar los datos
                    jButtonModfiDatos.setEnabled(true);

                }

            }
            // El telefono no existe en la base de datos:
            jTextFieldTelefono.setEnabled(false);
            jTextField2Nombre.setEnabled(true);
            jTextField3Direccion.setEnabled(true);
            jTextField4Numero.setEnabled(true);
            jTextField5Piso.setEnabled(true);
            jTextField7Puerta.setEnabled(true);
            jTextField1Portal.setEnabled(true);
            jTextField2Escalera.setEnabled(true);
            //jTextField7Puerta.setEditable(false);
            jButton1.setVisible(true);
            jButtonAceptar.setVisible(false);
            jButton2AceptarDatosNuevos.setVisible(true);

            //            //Liberar los objetos creados
            resul.close();
            sentencia.close();
            conexion.close();

        } catch (ClassNotFoundException ex) {
            System.out.println("Error con el driver de la base de datos ");

        } catch (SQLException ex) {
            System.out.println("Error en la conexión" + ex.toString());
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jTextFieldTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //CONEXIÓN A LA BASE DE DATOS
            try {
                //Asignar el driver de la base de datos.
                Class.forName("com.mysql.jdbc.Driver");
                //Establecemos la conexión con la base de datos.
                Connection conexion = DriverManager.getConnection("jdbc:mysql://sql7.freesqldatabase.com/sql7143904", "sql7143904", "TzNhGaxJj6");
                //Realizar la consulta y recoger el resultado en un objeto ResulSet.
                Statement sentencia = conexion.createStatement();
                int telefono = Integer.parseInt(jTextFieldTelefono.getText());
                ResultSet resul = sentencia.executeQuery("Select nombre,calle, numero,piso,puerta,portal,escalera from clientes where telefono=" + telefono + "");
                //Mostrar el resultado de la consulta.

                while (resul.next()) {
                    if (resul.getString(1).equals(0)) {
                        JOptionPane.showMessageDialog(rootPane, "¡No existe empleado con esa clave! ");

                        //System.out.println(telefono);
                    } else {
                        jTextField2Nombre.setText(resul.getString(1));
                        jTextField3Direccion.setText(resul.getString(2));
                        jTextField4Numero.setText(String.valueOf(resul.getInt(3)));
                        jTextField5Piso.setText(resul.getString(4));
                        jTextField7Puerta.setText(resul.getString(5));
                        jTextField1Portal.setText(resul.getString(6));
                        jTextField2Escalera.setText(resul.getString(7));
                        //Existe el cliente, por lo que anulamos el poder editar los campos.
                        //Y anulamos el botón aceptar.
                        jButtonAceptar.setEnabled(false);
                        jTextField2Nombre.setEditable(false);
                        jTextField3Direccion.setEditable(false);
                        jTextField4Numero.setEditable(false);
                        jTextField1Portal.setEditable(false);
                        jTextField2Escalera.setEditable(false);
                        jTextField5Piso.setEditable(false);

                        //Existe el cliente, por lo que podemos modificar los datos
                        jButtonModfiDatos.setEnabled(true);

                    }

                }
                // El telefono no existe en la base de datos:
                jTextFieldTelefono.setEnabled(false);
                jTextField2Nombre.setEnabled(true);
                jTextField3Direccion.setEnabled(true);
                jTextField4Numero.setEnabled(true);
                jTextField5Piso.setEnabled(true);
                jTextField7Puerta.setEnabled(true);
                jTextField1Portal.setEnabled(true);
                jTextField2Escalera.setEnabled(true);
                //jTextField7Puerta.setEditable(false);
                jButton1.setVisible(true);
                jButtonAceptar.setVisible(false);
                jButton2AceptarDatosNuevos.setVisible(true);

                //            //Liberar los objetos creados
                resul.close();
                sentencia.close();
                conexion.close();

            } catch (ClassNotFoundException ex) {
                System.out.println("Error con el driver de la base de datos ");

            } catch (SQLException ex) {
                System.out.println("Error en la conexión " + ex.toString());
            }
        }
    }//GEN-LAST:event_jTextFieldTelefonoKeyReleased

    private void jTextFieldTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoFocusLost
        // // Evento para cambiar el fondo cuando el campo telefono pierde el foco.
        jTextFieldTelefono.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextFieldTelefonoFocusLost

    private void jTextFieldTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoFocusGained
        // Evento para cambiar el fondo cuando el campo telefono tiene el foco.
        jTextFieldTelefono.setBackground(Color.PINK);
    }//GEN-LAST:event_jTextFieldTelefonoFocusGained

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // Boton abortar
        int respuesta = JOptionPane.showConfirmDialog(rootPane, "¿Seguro que desea salir?", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == 0) {
            this.dispose();
            JFrameMenu menu = new JFrameMenu(n);
            Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
            int height = pantalla.height;
            int width = pantalla.width;
            menu.setSize(width / 2, height / 2);

            menu.setLocationRelativeTo(null);
            menu.setVisible(true);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        NewJFrame jframeClave = new NewJFrame();
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        jframeClave.setSize(width / 2, height / 2);

        jframeClave.setLocationRelativeTo(null);
        jframeClave.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewJFrame1().setVisible(true);
//
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2AceptarDatosNuevos;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonModfiDatos;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2Nombre;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3Direccion;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4Numero;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel5Piso;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel6Puerta;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1Portal;
    private javax.swing.JTextField jTextField2Escalera;
    private javax.swing.JTextField jTextField2Nombre;
    private javax.swing.JTextField jTextField3Direccion;
    private javax.swing.JTextField jTextField4Numero;
    private javax.swing.JTextField jTextField5Piso;
    private javax.swing.JTextField jTextField7Puerta;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        list.setBackground(Color.RED);
        jComboBox1.setBackground(Color.GREEN);
        if (isSelected) {
            list.setBackground(Color.GREEN);

        }
        list.setBackground(Color.red);
        return this;
    }
}
